version: "3.5"

services:
  api:
    environment:
      NODE_ENV: production
      PORT: 4000
    ports:
      - "4000:4000"

  database:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: -----
      POSTGRES_PASSWORD: -----
      POSTGRES_DB: mannacode

volumes:
  pgdata:
