version: '3'

services:
  db:
    container_name: postgres-mannacode
    image: postgres
    environment: 
      - 'POSTGRES_DB=mannacode'
      - 'POSTGRES_USER=dev'
      - 'POSTGRES_PASSWORD=dev'
    ports:
      - '5432:5432'
  redis:
    container_name: redis-mannacode
    image: redis:5
    ports:
      - '6379:6379'