version: '3'

services:
  postgres:
    container_name: postgres-mannacodetest
    image: postgres
    environment: 
      - 'POSTGRES_DB=mannacodetest'
      - 'POSTGRES_USER=test'
      - 'POSTGRES_PASSWORD=test'
    ports:
      - '5432:5432'

  redis:
    container_name: redis-mannacode
    image: redis:5
    ports:
      - '6379:6379'