import { Application } from '../declarations';
import iusers from './iusers/iusers.service';
import users from './users/users.service';
import sendemailconfirm from './sendemailconfirm/sendemailconfirm.service';
import mailer from './mailer/mailer.service';
import verify from './verify/verify.service';
import igroup_challenges from './igroup-challenges/igroup-challenges.service';
import group_challenges from './group-challenges/group-challenges.service';
import group_challenges_status from './group-challenges-status/group-challenges-status.service';
import group_challenges_one_to_many from './group-challenges-one-to-many/group-challenges-one-to-many.service';
import ichallenges from './ichallenges/ichallenges.service';
import challenges from './challenges/challenges.service';
import challenge_players_finalized from './challenge-players-finalized/challenge-players-finalized.service';
import applicator_start from './applicator-start/applicator-start.service';
import applicator_start_group_challenge from './applicator-start-group-challenge/applicator-start-group-challenge.service';
import applicator_start_socket from './applicator-start-socket/applicator-start-socket.service';
import applicator_next_challenge from './applicator-next-challenge/applicator-next-challenge.service';
import applicator_start_solo from './applicator-start-solo/applicator-start-solo.service';
import iapplicator_start from './iapplicator-start/iapplicator-start.service';
import iplayer_start from './iplayer-start/iplayer-start.service';
import player_start from './player-start/player-start.service';
import player_start_solo from './player-start-solo/player-start-solo.service';
import player_challenges from './player-challenges/player-challenges.service';
import player_finalized_challenge from './player-finalized-challenge/player-finalized-challenge.service';
import player_test from './player-test/player-test.service';
import status_challenges from './status-challenges/status-challenges.service';
import status_players from './status-players/status-players.service';
import nex_player_challenges from './next-player-challenges/next-player-challenges.service';
import player_termineted_challenges from './player-terminated-challenges/player-terminated-challenges.service';
import player_challenge_punctuations from './player-challenge-punctuations/player-challenge-punctuations.service';
import iapplicator_challenge_punctuations from './iapplicator-challenge-punctuations/iapplicator-challenge-punctuations.service';
import applicator_challenge_punctuations from './applicator-challenge-punctuations/applicator-challenge-punctuations.service';
import applicator_player_finalized_challenge from './applicator-player-finalized-challenge/applicator-player-finalized-challenge.service';
import code_exeecutor from './code-executor/code-executor.service';
import applicator_test from './applicator-test/applicator-test.service';
import iplayer_challenges from './iplayer-challenges/iplayer-challenges.service';
import password from './password/password.service';
import plans from './plans/plans.service';
import iplans from './iplans/iplans.service';
import class_player from './class-player/class-player.service';
import authentication_player from './authentication-player/authentication-player.service';

export default function(app: Application): void {
  app.configure(iusers);
  app.configure(users);
  app.configure(sendemailconfirm);
  app.configure(mailer);
  app.configure(verify);
  app.configure(igroup_challenges);
  app.configure(group_challenges);
  app.configure(group_challenges_status);
  app.configure(group_challenges_one_to_many);
  app.configure(ichallenges);
  app.configure(challenges);
  app.configure(challenge_players_finalized);
  app.configure(iapplicator_start);
  app.configure(applicator_start);
  app.configure(applicator_start_solo);
  app.configure(applicator_start_socket);
  app.configure(applicator_next_challenge);
  app.configure(iplayer_start);
  app.configure(player_start);
  app.configure(player_start_solo);
  app.configure(player_challenges);
  app.configure(player_finalized_challenge);
  app.configure(player_test);
  app.configure(status_challenges);
  app.configure(status_players);
  app.configure(nex_player_challenges);
  app.configure(player_termineted_challenges);
  app.configure(player_challenge_punctuations);
  app.configure(iapplicator_challenge_punctuations);
  app.configure(applicator_challenge_punctuations);
  app.configure(applicator_player_finalized_challenge);
  app.configure(code_exeecutor);
  app.configure(applicator_test);
  app.configure(iplayer_challenges);
  app.configure(applicator_start_group_challenge);
  app.configure(password);
  app.configure(iplans);
  app.configure(plans);
  app.configure(class_player);
  app.configure(authentication_player);
}
